version: '2'

services:
  mongodb:
    image: library/mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: mep_bonds
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  cotizacion-mep-bot:
    build: ./
    container_name: cotizacion-mep-bot
    environment:
      TELEGRAM_TOKEN: $telegram_token
      API_URL: $api_url

  cotizacion-mep-api:
    build: ../cotizacion-mep
    container_name: cotizacion-mep-api
    environment:
      username: ${username}
      password: ${password}
    ports:
      - "5000:5000/tcp"

volumes:
  db:
